// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nljdisncbbhnpblaivje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5samRpc25jYmJobnBibGFpdmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjEwODEsImV4cCI6MjA3NDY5NzA4MX0.owxA2-8rqdcR2iVgW6qDwOt4iMNRpIcgxWwt1Tyal5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});